[versions]
accompanistPermissions = "0.37.3"
agp = "9.4.1"
composeMaterial3 = "1.6.2"
converterGson = "3.0.0"
datastore = "1.2.1"
glance = "1.2.0"
hiltWork = "1.4.0"
kotlin = "2.4.20"
ksp = "2.2.20-2.0.2"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.8.0"
kotlinxSerializationJson = "1.11.0"
leakcanaryAndroid = "2.14"
lifecycleViewmodelCompose = "2.11.0"

hiltAndroid = "2.60.1"
hiltNavigationCompose = "1.4.0"

materialIconsExtended = "1.7.8"
navigationCompose = "2.10.1"
playServicesWearable = "20.0.1"
material = "1.14.0"
composeBom = "2026.09.00"
material3Android = "1.5.0-alpha28"
activityCompose = "1.13.0"
coreSplashscreen = "1.2.0"
retrofitVersion = "3.0.0"
tiles = "1.6.2"
tilesMaterial = "1.6.2"
horologistComposeTools = "0.7.15"
horologistTiles = "0.7.15"
versionTrackerAndroidLibrary = "0.0.1"
watchfaceComplicationsDataSourceKtx = "1.3.0"

googleServices = "4.5.0"
workRuntime = "2.11.2"
lifecycleRuntimeKtx = "2.11.0"
aboutlibrariesCore = "15.2.0"
firebaseCrashlytics = "20.1.1"
googleFirebaseCrashlytics = "3.0.8"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-compose-material3 = { module = "androidx.wear.compose:compose-material3", version.ref = "composeMaterial3" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-tiles = { group = "androidx.wear.tiles", name = "tiles", version.ref = "tiles" }
androidx-tiles-material = { group = "androidx.wear.tiles", name = "tiles-material", version.ref = "tilesMaterial" }
horologist-compose-tools = { group = "com.google.android.horologist", name = "horologist-compose-tools", version.ref = "horologistComposeTools" }
horologist-tiles = { group = "com.google.android.horologist", name = "horologist-tiles", version.ref = "horologistTiles" }
androidx-watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }

firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
version-tracker-android-library = { module = "com.github.sai-charan2003:Version-Tracker-Android-Library", version.ref = "versionTrackerAndroidLibrary" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibrariesCore" }

[bundles]
compose-mobile = [
    "androidx-activity-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-material-icons-extended",
    "androidx-material3-android",
    "androidx-navigation-compose",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
]
compose-wear = [
    "androidx-activity-compose",
    "androidx-compose-material3",
    "androidx-material-icons-extended",
    "androidx-ui",
    "androidx-ui-tooling-preview",
]
compose-debug = [
    "androidx-ui-test-manifest",
    "androidx-ui-tooling",
]
glance = [
    "androidx-glance",
    "androidx-glance-appwidget",
]
wear-tiles = [
    "androidx-tiles",
    "androidx-tiles-material",
    "horologist-compose-tools",
    "horologist-tiles",
]
hilt-mobile = [
    "androidx-hilt-navigation-compose",
    "androidx-hilt-work",
    "hilt-android",
]
retrofit = [
    "converter-gson",
    "retrofit",
]
test-android = [
    "androidx-espresso-core",
    "androidx-junit",
    "androidx-ui-test-junit4",
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
mikepenz-aboutlibrary = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibrariesCore" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
